Pull Docker image after login

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -46,13 +46,26 @@ jobs:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
 
-    - name: Check if Docker image exists
+    - name: Attempt to pull Docker image
       id: check_image
       run: |
-        if ! docker pull tep-core:latest --quiet; then
-          echo "Image tep-core:latest does not exist or access denied."
-          exit 1
+        if ! docker pull tep-core:latest 2>&1 | tee output.log | grep -q 'requested access to the resource is denied'; then
+          echo "Image tep-core:latest does not require login."
+        else
+          echo "Image tep-core:latest requires login."
+          echo "login_required=true" >> $GITHUB_ENV
         fi
+  
+    - name: Login to Docker Hub if required
+      if: env.login_required == 'true'
+      uses: docker/login-action@v3
+      with:
+        username: ${{ secrets.DOCKER_USERNAME }}
+        password: ${{ secrets.DOCKER_PASSWORD }}
+
+    - name: Pull Docker image after login
+      if: env.login_required == 'true'
+      run: docker pull tep-core:latest
 
     - name: Set up Docker Compose Action
       uses: hoverkraft-tech/compose-action@v2.0.1
